name: general-tests

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

on: [pull_request]

jobs:
  general-tests-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        github-server-url: https://github.com/dogusyuksel/golden-sample
        lfs: true

    - name: Download Repos
      run: |
        git submodule update --init --recursive

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Project Docker
      uses: docker/build-push-action@v5
      with:
        load: true
        tags: |
          ${{ secrets.DOCKER_REPO }}:master
        context: .
        file: docker/Dockerfile
        pull: true
        push: false
        provenance: false

    - name: Dirty Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/scripts && ./dirty_check.sh"

    - name: Format Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/scripts && ./format_check.sh"

    - name: SPLint Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/scripts && ./lint_check.sh"

    - name: Unit Test
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/scripts && ./run_unittests.sh"

    - name: glibc Build Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/glibc && make all"

    - name: tools Build Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/sw_tools && make all"

    - name: can_dump Build Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/sw_tools/can_dump && ./build.sh"

    - name: json_parser Build Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/sw_tools/json_parser && ./build.sh"

    - name: custom Build Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/hw_tools && ./download_repos.sh && ./bake.sh all clean build"

    - name: hal Build Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/hal/build && ./build_all.sh"

    - name: rtos Build Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/rtos/build && ./build_all.sh"

    - name: stlink check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "st-info  --version"

    - name: pytest
      run: |
         ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/python/extended-grep && pytest"

    - name: flake8
      run: |
         echo "'isort .' can be executed if needed"
         ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/python && flake8 --max-line-length=120"
