name: general-tests
# Builds release dockers for ops-release, tagging them with the ops tag given

on: [push, pull_request]

jobs:
  general-tests-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        github-server-url: https://github.com/dogusyuksel/cicd-example.git
        lfs: true

    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          dockerfile:
            - 'docker/**'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Project Docker
      uses: docker/build-push-action@v5
      with:
        load: true
        tags: |
          ${{ secrets.DOCKER_REPO }}:master
        context: .
        file: docker/Dockerfile
        pull: true
        push: false
        provenance: false

    - name: Build Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd bitbake/buildandtest/ && source environment && bitbake buildgcc:do_build ; cat tmp/buildgcc/work/log.do_build && bitbake buildebug:do_build ; cat tmp/buildebug/work/log.do_build"

    - name: valgrind Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd bitbake/buildandtest/ && source environment && bitbake testall ; cat tmp/testall/work/log.do_build"

    - name: Dirty Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd scripts && ./dirty_check.sh"

    - name: Format Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd scripts && ./format_check.sh"

    - name: SPLint Check
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd scripts && ./lint_check.sh"

    - name: Unit Test
      run: |
        ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd scripts && ./run_unittests.sh"

    - name: Checkout basic-C-linter
      uses: actions/checkout@v2
      with:
        repository: dogusyuksel/basic-C-linter
        path: './basic-C-linter'

    - name: Build basic-C-linter
      run: |
         cd basic-C-linter
         make

    - name: Run basic-C-linter
      run: |
         ./basic-C-linter/analyzer -d ./ceedling/myproject/src

    - name: Hadolint Check
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: docker/Dockerfile
        failure-threshold: error

    - name: pytest
      run: |
         ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace/python/custom_echo && pytest"

    - name: flake8
      run: |
         echo "'isort .' can be executed if needed"
         ./docker/run_docker.sh ${{ secrets.DOCKER_REPO }}:master "cd /workspace && flake8 --max-line-length=120"

    - name: Push Project Docker
      if: steps.changes.outputs.dockerfile == 'true'
      uses: docker/build-push-action@v5
      with:
        tags: |
          ${{ secrets.DOCKER_REPO }}:master
        context: .
        file: docker/Dockerfile
        pull: true
        push: true
        provenance: false
